# Generated by Django 5.0.6 on 2026-04-09 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courriers', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Enregistrement'), ('SCAN', 'Scan document'), ('DISPATCH', 'Dispatch service'), ('AFFECTATION', 'Affectation agent'), ('INSTRUCTION', 'Instruction chef'), ('CONSULTATION', 'Consultation'), ('COMMENTAIRE', 'Commentaire'), ('VALIDATION', 'Validation'), ('CLOTURE', 'Clôture'), ('PJ_AJOUT', 'PJ ajoutée'), ('PJ_SUPPR', 'PJ supprimée'), ('LIEN_CREE', 'Lien créé'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('statut_avant', models.CharField(blank=True, max_length=20)),
                ('statut_apres', models.CharField(blank=True, max_length=20)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='courriers.courrier')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='organisations.service')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_mouvement'],
                'indexes': [models.Index(fields=['courrier', 'date_mouvement'], name='mouvements__courrie_f21bfe_idx'), models.Index(fields=['utilisateur', 'date_mouvement'], name='mouvements__utilisa_25c8af_idx')],
            },
        ),
    ]
