# Generated by Django 5.0.6 on 2026-04-09 08:49

import apps.courriers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('parametrage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('PERSONNE', 'Personne'), ('SERVICE', 'Service'), ('INSTITUTION', 'Institution'), ('SOCIETE', 'Société')], default='SERVICE', max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Expediteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('PERSONNE', 'Personne physique'), ('SOCIETE', 'Société'), ('INSTITUTION', 'Institution'), ('AMBASSADE', 'Ambassade'), ('SERVICE', 'Service interne')], default='INSTITUTION', max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pays', models.CharField(default='Niger', max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('date_reception', models.DateField()),
                ('objet', models.TextField()),
                ('sens', models.CharField(choices=[('ENT', 'Entrant'), ('SOR', 'Sortant'), ('INT', 'Interne')], max_length=3)),
                ('canal', models.CharField(choices=[('POSTE', 'Poste'), ('EMAIL', 'E-mail'), ('DEPOT', 'Dépôt guichet'), ('FAX', 'Fax'), ('COURSIER', 'Coursier'), ('INTERNE', 'Interne')], default='DEPOT', max_length=20)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('confidentiel', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('agent_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_en_charge', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_crees', to=settings.AUTH_USER_MODEL)),
                ('priorite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers', to='parametrage.priorite')),
                ('service_destinataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_recus', to='organisations.service')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers', to='parametrage.statutcourrier')),
                ('type_courrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers', to='parametrage.typecourrier')),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_expedies', to='courriers.expediteur')),
            ],
            options={
                'ordering': ['-date_enregistrement', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LienCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('REPONSE_A', 'Réponse à'), ('RELANCE', 'Relance de'), ('ANNULATION', 'Annulation de'), ('SUITE_A', 'Suite à'), ('REFERENCE', 'Référence à')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('courrier_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_cible', to='courriers.courrier')),
                ('courrier_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_source', to='courriers.courrier')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=apps.courriers.models._chemin_pj)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('taille_ko', models.FloatField(default=0)),
                ('est_scan', models.BooleanField(default=False)),
                ('uploade_le', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='courriers.courrier')),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploade_le'],
            },
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['numero'], name='courriers_c_numero_6b4808_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['sens', 'statut'], name='courriers_c_sens_367556_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['service_destinataire', 'statut'], name='courriers_c_service_b9f6da_idx'),
        ),
        migrations.AddIndex(
            model_name='courrier',
            index=models.Index(fields=['date_echeance'], name='courriers_c_date_ec_02da36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='liencourrier',
            unique_together={('courrier_source', 'courrier_cible', 'type_lien')},
        ),
    ]
