# Generated by Django 5.0.6 on 2026-04-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='courrier',
            name='reference_externe',
        ),
    ]
