# Generated by Django 5.0.6 on 2026-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0002_remove_courrier_canal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='pour',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
