# Generated by Django 5.0.6 on 2026-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0003_courrier_pour'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='imp',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('COPIE', 'Copie')], default='ORIGINAL', max_length=10),
        ),
    ]
