# Generated by Django 5.0.6 on 2026-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0004_courrier_imp'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='numero_lettre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
