# Generated by Django 5.0.6 on 2026-04-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0005_courrier_date_sortie_courrier_numero_lettre'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='service_copie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_copie', to='organisations.service'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='service_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_original', to='organisations.service'),
        ),
    ]
