# Generated by Django 5.0.6 on 2026-05-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courriers', '0008_add_manytomany_imputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courrier',
            name='service_copie',
        ),
        migrations.RemoveField(
            model_name='courrier',
            name='service_original',
        ),
        migrations.AddField(
            model_name='courrier',
            name='avis_sg',
            field=models.TextField(blank=True, verbose_name='Observations SG'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='avis_sg_positif',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='avis_sga',
            field=models.TextField(blank=True, verbose_name='Observations SGA'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='avis_sga_positif',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_entree_min',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_entree_sg',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_entree_sga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_sortie_min',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_sortie_sg',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='date_sortie_sga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='decision_min',
            field=models.TextField(blank=True, verbose_name='Décision du Ministre'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='decision_min_positif',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
