# Generated by Django 5.0.6 on 2026-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('delai_jours', models.PositiveSmallIntegerField(default=15)),
                ('couleur', models.CharField(choices=[('primary', 'Bleu'), ('success', 'Vert'), ('warning', 'Orange'), ('danger', 'Rouge'), ('secondary', 'Gris'), ('info', 'Cyan'), ('dark', 'Noir')], default='secondary', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'priorité',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StatutCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('couleur', models.CharField(choices=[('primary', 'Bleu'), ('success', 'Vert'), ('warning', 'Orange'), ('danger', 'Rouge'), ('secondary', 'Gris'), ('info', 'Cyan'), ('dark', 'Noir')], default='secondary', max_length=20)),
                ('est_final', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'statut de courrier',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='TypeCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'type de courrier',
                'ordering': ['ordre', 'libelle'],
            },
        ),
    ]
